name: 'Code Scanning Analysis CSV'
description: 'Gets code scanning analyses from repos and generates a CSV.'

branding:
  icon: 'file-text'
  color: 'blue'

inputs:
  TOKEN:
    description: 'GitHub Token or Personal Access Token  - must use PAT to access alerts for repos other
      than the repo where the action is used.'
    required: true
  path:
    description: 'Path to the directory where the csv file should be saved.'
    required: true
  total_days:
    description: 'Integer - fetches repo analyses for the past total_days. For example, if total_days is
      set `7`, the action will get code scanning analyses that were created in the past seven days.
      Minimum is 1 day and max is 365 days. Defaults to `7`.'
    required: false
  repos:
    description: 'Comma-separated list of repository names from which code scanning analyses should be
      fetched. For example, `best-app,cool-app`. The repos must be in the org where the action is used.
      Set to `all` for code scanning analyses from all repos in the org. When `repos` is not set, the
      action will get code scanning analyses for the repo where it is used. When `repos` is set, include
      the repo where the action is used to get code scanning analyses for that repo.'
    required: false

runs:
  using: 'node20'
  main: 'dist/index.js'
